[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = true

[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"
font = "sans serif"

[browser]
gatherUsageStats = false

[runner]
magicEnabled = true
